# Generated by Django 2.2.3 on 2022-10-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linebosses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPiezas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(choices=[('P1', 'PIEZA 1'), ('P2', 'PIEZA 2'), ('P3', 'PIEZA 3')], default='PIEZA 1', max_length=32)),
                ('cantdad_pieza', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(choices=[('P1', 'PIEZA 1'), ('P2', 'PIEZA 2'), ('P3', 'PIEZA 3')], default='PIEZA 1', max_length=32)),
                ('no_order', models.IntegerField(default='0')),
                ('lineboss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='linebosses.LineBosses')),
            ],
        ),
    ]
