# Generated by Django 2.2.3 on 2022-10-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0002_registrodeentrega_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeentrega',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
