# Generated by Django 2.2.3 on 2022-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0005_auto_20221020_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeentrega',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
